In [1]:
import random
import numpy as np

In [2]:
#number of vertices
n=int(input('number of vertices: '))
graph = np.zeros((n,n),dtype=int)

number of vertices: 4


In [3]:
#number of edges if its complete 
MaxEdges=(n*(n-1))//2
print(f'number of edges if graph is completed :{MaxEdges}')

number of edges if graph is completed :6


In [4]:
#number of edges
m=random.randint(0,(MaxEdges-1))
print(f'number of edges {m}: ')

number of edges 4: 


In [5]:
#create random graph
r=0
while r<m:
    i=random.randint(0,(n-1))
    j=random.randint(0,(n-1))
    if i!=j:
        if graph[i][j]==0:
            graph[i][j]=1
            graph[j][i]=1
            r=r+1   
print(graph)

[[0 0 1 1]
 [0 0 0 1]
 [1 0 0 1]
 [1 1 1 0]]


In [6]:
#number of colors
NumColors=int(input('number of colors: '))
#Nodes coloring
Nodes = [-1 for i in range(n)]

number of colors: 3


In [7]:
ForwardFiltering=[[i for i in range(NumColors)] for i in range(n)]

In [8]:
def Forward_Filtering(node,color):
    for j in range(n):#loop between neighbors
        if graph[node][j]==1:#check if they are connected
            if color in  ForwardFiltering[j]:
                ForwardFiltering[j].remove(color)

In [9]:
def ConstraintCheck(node,color):
    for j in range(n):#loop between neighbors
        if graph[node][j]==1:#check if they are connected
            if Nodes[j]==color:#check if they are same color
                return False
    return True

In [10]:
def SolveBackTracking(node):
#base 
    if node==n:
        return True
#check constration and backtracking
    for color in range(NumColors):#loop between colors
        if(ConstraintCheck(node,color)):
            Forward_Filtering(node,color)
            Nodes[node]=color
            print(Nodes)
            SolveBackTracking(node+1)
#check for forward filtering
    for i in ForwardFiltering:
        if len(i)==0:
            return False

In [11]:
if SolveBackTracking(0)==False:
    print('Can not color this graph with this number of colors')
else:
    print('Can color this graph with this number of colors and assigned colors:')
    for i in range(len(Nodes)):
        print(f'Node {i} th is colored by color number {Nodes[i]}')

[0, -1, -1, -1]
[0, 0, -1, -1]
[0, 0, 1, -1]
[0, 0, 1, 2]
[0, 1, 1, 2]
[0, 1, 1, 2]
[0, 1, 1, 2]
Can color this graph with this number of colors and assigned colors:
Node 0 th is colored by color number 0
Node 1 th is colored by color number 1
Node 2 th is colored by color number 1
Node 3 th is colored by color number 2
